# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import query_pb2 as query__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrace = channel.unary_stream(
                '/jaeger.api_v2.QueryService/GetTrace',
                request_serializer=query__pb2.GetTraceRequest.SerializeToString,
                response_deserializer=query__pb2.SpansResponseChunk.FromString,
                _registered_method=True)
        self.ArchiveTrace = channel.unary_unary(
                '/jaeger.api_v2.QueryService/ArchiveTrace',
                request_serializer=query__pb2.ArchiveTraceRequest.SerializeToString,
                response_deserializer=query__pb2.ArchiveTraceResponse.FromString,
                _registered_method=True)
        self.FindTraces = channel.unary_stream(
                '/jaeger.api_v2.QueryService/FindTraces',
                request_serializer=query__pb2.FindTracesRequest.SerializeToString,
                response_deserializer=query__pb2.SpansResponseChunk.FromString,
                _registered_method=True)
        self.GetServices = channel.unary_unary(
                '/jaeger.api_v2.QueryService/GetServices',
                request_serializer=query__pb2.GetServicesRequest.SerializeToString,
                response_deserializer=query__pb2.GetServicesResponse.FromString,
                _registered_method=True)
        self.GetOperations = channel.unary_unary(
                '/jaeger.api_v2.QueryService/GetOperations',
                request_serializer=query__pb2.GetOperationsRequest.SerializeToString,
                response_deserializer=query__pb2.GetOperationsResponse.FromString,
                _registered_method=True)
        self.GetDependencies = channel.unary_unary(
                '/jaeger.api_v2.QueryService/GetDependencies',
                request_serializer=query__pb2.GetDependenciesRequest.SerializeToString,
                response_deserializer=query__pb2.GetDependenciesResponse.FromString,
                _registered_method=True)


class QueryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindTraces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDependencies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrace': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTrace,
                    request_deserializer=query__pb2.GetTraceRequest.FromString,
                    response_serializer=query__pb2.SpansResponseChunk.SerializeToString,
            ),
            'ArchiveTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveTrace,
                    request_deserializer=query__pb2.ArchiveTraceRequest.FromString,
                    response_serializer=query__pb2.ArchiveTraceResponse.SerializeToString,
            ),
            'FindTraces': grpc.unary_stream_rpc_method_handler(
                    servicer.FindTraces,
                    request_deserializer=query__pb2.FindTracesRequest.FromString,
                    response_serializer=query__pb2.SpansResponseChunk.SerializeToString,
            ),
            'GetServices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServices,
                    request_deserializer=query__pb2.GetServicesRequest.FromString,
                    response_serializer=query__pb2.GetServicesResponse.SerializeToString,
            ),
            'GetOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperations,
                    request_deserializer=query__pb2.GetOperationsRequest.FromString,
                    response_serializer=query__pb2.GetOperationsResponse.SerializeToString,
            ),
            'GetDependencies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDependencies,
                    request_deserializer=query__pb2.GetDependenciesRequest.FromString,
                    response_serializer=query__pb2.GetDependenciesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jaeger.api_v2.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jaeger.api_v2.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jaeger.api_v2.QueryService/GetTrace',
            query__pb2.GetTraceRequest.SerializeToString,
            query__pb2.SpansResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jaeger.api_v2.QueryService/ArchiveTrace',
            query__pb2.ArchiveTraceRequest.SerializeToString,
            query__pb2.ArchiveTraceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindTraces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jaeger.api_v2.QueryService/FindTraces',
            query__pb2.FindTracesRequest.SerializeToString,
            query__pb2.SpansResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jaeger.api_v2.QueryService/GetServices',
            query__pb2.GetServicesRequest.SerializeToString,
            query__pb2.GetServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jaeger.api_v2.QueryService/GetOperations',
            query__pb2.GetOperationsRequest.SerializeToString,
            query__pb2.GetOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDependencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jaeger.api_v2.QueryService/GetDependencies',
            query__pb2.GetDependenciesRequest.SerializeToString,
            query__pb2.GetDependenciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
