"""Configuration defaults and overrides."""

from otel_etl.config.defaults import (
    DEFAULT_CARDINALITY_THRESHOLDS,
    DEFAULT_TIER_ACTIONS,
    DEFAULT_TOP_N,
    DEFAULT_PROFILING_WINDOW_HOURS,
    DEFAULT_AGGREGATION_WINDOW_SECONDS,
)

__all__ = [
    "DEFAULT_CARDINALITY_THRESHOLDS",
    "DEFAULT_TIER_ACTIONS",
    "DEFAULT_TOP_N",
    "DEFAULT_PROFILING_WINDOW_HOURS",
    "DEFAULT_AGGREGATION_WINDOW_SECONDS",
]
