// Package smlprocessor implements the SymetryML metrics processor for the
// OpenTelemetry Collector. It receives OTLP metrics, converts them to a
// godf DataFrame, runs the denormalize_metrics pipeline, and emits the
// resulting wide-format features as new OTel metrics.
package smlprocessor

import (
	"go.opentelemetry.io/collector/component"
)

// Config holds the processor configuration.
//
// All fields can be set in the collector YAML config. Additionally, each
// field can be overridden by an environment variable (env var takes precedence):
//
//	services         → SML_SERVICES (comma-separated, empty = all)
//	service_label    → SML_SERVICE_LABEL (default: service_name)
//	schema_path      → SML_SCHEMA_PATH
//	window_seconds   → SML_WINDOW_SECONDS
//	include_deltas   → SML_INCLUDE_DELTAS
//	entity_labels    → SML_ENTITY_LABELS (comma-separated)
//	force_drop_labels→ SML_FORCE_DROP_LABELS (comma-separated)
//	sanitize_names   → SML_SANITIZE_NAMES (default: true)
type Config struct {
	// Services filters incoming metrics to only these service names.
	// Empty list means process all services.
	// Env override: SML_SERVICES (comma-separated, e.g. "checkout,frontend")
	Services []string `mapstructure:"services"`
	// ServiceLabel is the label name used to identify the service (default: "service_name").
	// Env override: SML_SERVICE_LABEL
	ServiceLabel string `mapstructure:"service_label"`
	// SchemaPath is the path to a schema YAML file (generated by profiler or manually).
	// Env override: SML_SCHEMA_PATH
	SchemaPath string `mapstructure:"schema_path"`
	// WindowSeconds is the aggregation window (default: 60).
	// Env override: SML_WINDOW_SECONDS
	WindowSeconds float64 `mapstructure:"window_seconds"`
	// IncludeDeltas enables delta/pct-change feature computation (default: true).
	// Env override: SML_INCLUDE_DELTAS
	IncludeDeltas bool `mapstructure:"include_deltas"`
	// DeltaWindows lists shift amounts for delta features (default: [5, 60]).
	DeltaWindows []int `mapstructure:"delta_windows"`
	// EntityLabels overrides entity key labels (default: auto-detect).
	// Env override: SML_ENTITY_LABELS (comma-separated)
	EntityLabels []string `mapstructure:"entity_labels"`
	// ForceDropLabels are labels to always remove before processing.
	// Env override: SML_FORCE_DROP_LABELS (comma-separated)
	ForceDropLabels []string `mapstructure:"force_drop_labels"`
	// SanitizeNames converts dots and dashes in metric/label names to underscores
	// to match Prometheus-profiled schemas (default: true).
	// Env override: SML_SANITIZE_NAMES
	SanitizeNames *bool `mapstructure:"sanitize_names"`
}

func createDefaultConfig() component.Config {
	t := true
	return &Config{
		WindowSeconds: 60,
		IncludeDeltas: true,
		DeltaWindows:  []int{5, 60},
		SanitizeNames: &t,
	}
}
