# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\x14\x64\x61tadog.agentpayload\"C\n\rMetricPayload\x12\x32\n\x06series\x18\x01 \x03(\x0b\x32\".datadog.agentpayload.MetricSeries\"\xf6\x01\n\x0cMetricSeries\x12\x31\n\tresources\x18\x01 \x03(\x0b\x32\x1e.datadog.agentpayload.Resource\x12\x0e\n\x06metric\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12+\n\x06points\x18\x04 \x03(\x0b\x32\x1b.datadog.agentpayload.Point\x12.\n\x04type\x18\x05 \x01(\x0e\x32 .datadog.agentpayload.MetricType\x12\x0c\n\x04unit\x18\x06 \x01(\t\x12\x18\n\x10source_type_name\x18\x07 \x01(\t\x12\x10\n\x08interval\x18\x08 \x01(\x03\")\n\x05Point\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"&\n\x08Resource\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t*=\n\nMetricType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\t\n\x05\x43OUNT\x10\x01\x12\x08\n\x04RATE\x10\x02\x12\t\n\x05GAUGE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICTYPE']._serialized_start=440
  _globals['_METRICTYPE']._serialized_end=501
  _globals['_METRICPAYLOAD']._serialized_start=39
  _globals['_METRICPAYLOAD']._serialized_end=106
  _globals['_METRICSERIES']._serialized_start=109
  _globals['_METRICSERIES']._serialized_end=355
  _globals['_POINT']._serialized_start=357
  _globals['_POINT']._serialized_end=398
  _globals['_RESOURCE']._serialized_start=400
  _globals['_RESOURCE']._serialized_end=438
# @@protoc_insertion_point(module_scope)
