"""Datadog ETL configuration."""

from dd_etl.config.defaults import (
    DD_TAG_MAPPING,
    DD_TYPE_MAPPING,
    DD_HISTOGRAM_SUFFIXES,
    DEFAULT_FLUSH_INTERVAL_SECONDS,
    DEFAULT_BUFFER_RETENTION_HOURS,
    DEFAULT_PARQUET_PARTITION_MINUTES,
    INTAKE_ENDPOINTS,
)

__all__ = [
    "DD_TAG_MAPPING",
    "DD_TYPE_MAPPING",
    "DD_HISTOGRAM_SUFFIXES",
    "DEFAULT_FLUSH_INTERVAL_SECONDS",
    "DEFAULT_BUFFER_RETENTION_HOURS",
    "DEFAULT_PARQUET_PARTITION_MINUTES",
    "INTAKE_ENDPOINTS",
]
